### ISSUE TITLE
 Item display issues in galious enhanced v1.02

### ISSUE THREAD

**Issue by LOA2000GM** [bladeba/MSX#5]
Items that appear under certain conditions (ex : candle, sabre, dagger, vase) are not displayed. (Acquisition is possible)
I checked this on BLUEMSX.
Here's a comparison video between the original and ehnanced.
Thank you.

https://user-images.githubusercontent.com/104535067/165650972-ac52917e-024f-4be2-8561-66fc2106b3b7.mp4

**Comment by bladeba** [comment]
Fixed in version 1.03
