### ISSUE TITLE
World 10 last room issues in galious enhanced v1.03

### ISSUE THREAD

**Issue by LOA2000GM** [bladeba/MSX#6]
1. Can't break rocks with swords (can be done with sub-weapons)
2. The screen effect after finding the baby is not normal.
Please check the video below.

Thank you.

https://user-images.githubusercontent.com/104535067/166877731-e81ecf8a-461c-4b38-ab27-d7ebce5e75d9.mp4

**Comment by bladeba** [comment]
Fixed in version 1.04
